// Contact page content — exact copy ported from prototype/contact.html.
// This is the single source of truth: it renders as a fallback (so the page is
// a 1:1 replica with zero setup) AND seeds Sanity.
export const CONTACT_CONTENT = {
  hero: {
    breadcrumbHomeLabel: "Home",
    breadcrumbHomeHref: "/",
    breadcrumbSep: "→",
    breadcrumbCurrent: "Contact",
    headline: "Contact Us",
    subheadLead: "Coconut Grove Sailing Club Instructional Center.",
    subheadEm: "Reach the team directly — by phone, by email, or the note below.",
    locationChip: "2990 S. Bayshore Drive · Miami, FL 33133",
  },
  inquiry: {
    eyebrow: "Send a note",
    headline: "Tell us about the sailor.",
    sub: "A coach reads every inquiry and points you to the right program or course.",
    form: {
      eyebrow: "General inquiry",
      headlineLead: "Sail with us —",
      headlineEm: "where would you start?",
      helper:
        'No commitment, no fee. If you\'re not sure which program fits, mark "Help me figure it out" — we\'ll suggest one.',
      namePlaceholder: "Your name",
      emailPlaceholder: "Email",
      phonePlaceholder: "Phone (optional)",
      programDefaultOption: "Which program?",
      programOptions: [
        { label: "Adult Sailing" },
        { label: "Racing Teams — Junior" },
        { label: "Racing Teams — Senior / HPC" },
        { label: "Youth Sailing" },
        { label: "Private coaching" },
        { label: "Help me figure it out" },
      ],
      sailorInfoPlaceholder: "Sailor's name & age (if not you)",
      notesPlaceholder:
        "Anything else? Experience, dates that work, questions (optional)",
      submitLabel: "Send →",
    },
    info: {
      eyebrow: "Direct line",
      phoneLabel: "Phone",
      phoneHref: "tel:+13054444571",
      phoneText: "(305) 444-4571",
      phoneSmallPre: "Office hours ",
      phoneTbd: "TBD",
      emailLabel: "Email",
      emailHref: "mailto:icmanager@cgsc.org",
      emailText: "icmanager@cgsc.org",
      addressLabel: "Address",
      addressLine1: "2990 S. Bayshore Drive",
      addressSmall: "Miami, FL 33133",
      openHouseLabel: "Open house",
      openHouseTbd: "Cadence TBD",
      openHouseSmallPre: "Drop-ins welcome by appointment. See the ",
      openHouseLinkText: "calendar",
      openHouseLinkHref: "/calendar",
      openHouseSmallPost: " for confirmed dates.",
      foot: "Prefer a specific person? See the Instructional Center contacts below.",
    },
  },
  contacts: {
    eyebrow: "Who to reach",
    headline: "Instructional Center contacts.",
    sub: "Coconut Grove Sailing Club Instructional Center. Reach the team directly, or send the form above and a coach will route it.",
    people: [
      {
        photo: "/assets/coaches/maru.jpg",
        role: "Director of Sailing Performance",
        name: "Maru Urban",
        phoneText: "(305) 444-4571 ×11",
        phoneHref: "tel:+13054444571,11",
        emailText: "icdirector@cgsc.org",
        emailHref: "mailto:icdirector@cgsc.org",
      },
      {
        photo: "/assets/coaches/rosa.jpg",
        role: "Director of Programs & Development",
        name: "Rosa Lamela",
        phoneText: "(305) 444-4571 ×11",
        phoneHref: "tel:+13054444571,11",
        emailText: "icmanager@cgsc.org",
        emailHref: "mailto:icmanager@cgsc.org",
      },
      {
        photo: "/assets/coaches/lauren.jpg",
        role: "General Manager",
        name: "Lauren Simpson",
        phoneText: "(305) 444-4571 ×18",
        phoneHref: "tel:+13054444571,18",
        emailText: "info@cgsc.org",
        emailHref: "mailto:info@cgsc.org",
      },
    ],
    footPre: "CGSC Instructional Center is a 501(c)(3) nonprofit and part of ",
    clubLinkText: "Coconut Grove Sailing Club",
    clubLinkHref: "https://cgsc.org/",
    footMid: ". ",
    donateLinkText: "Donate →",
    donateLinkHref: "https://cgscic.org/donate/",
  },
  visit: {
    eyebrow: "Visit the dock",
    headline: "2990 S. Bayshore Drive.",
    prose:
      "We're on Biscayne Bay at **2990 S. Bayshore Drive** in Coconut Grove — the full CGSC fleet, dock, and coaching staff on site. The fastest way to know if CGSC is right for you is to walk down the dock and meet the boats, the water, and the coaches.",
    list: {
      officeHoursLabel: "Office hours",
      officeHoursTbd: "TBD — call ahead to confirm",
      openHouseLabel: "Open house",
      openHouseTbd: "Cadence TBD",
      openHouseTrailPre: " — see the ",
      calendarLinkText: "calendar",
      calendarLinkHref: "/calendar",
      openHouseTrailPost: " for confirmed dates",
    },
  },
  map: {
    eyebrow: "Find us",
    headline: "Coconut Grove waterfront.",
    sub: "Map embed lands in Phase 2 (Mapbox or static tile). For now, click through to Google Maps for directions.",
    name: "CGSC Instructional Center",
    address: "2990 S. Bayshore Drive · Miami, FL 33133",
    linkText: "Open in Google Maps →",
    linkHref:
      "https://www.google.com/maps/search/?api=1&query=2990+S+Bayshore+Drive+Miami+FL+33133",
  },
};

export type ContactContent = typeof CONTACT_CONTENT;
